home_nix_path = '/Users/picric_acid/.dotfiles/.config/home-manager/home.nix'
packages_file_path = '/Users/picric_acid/.dotfiles/.config/home-manager/focus-packages.nix'
use_flake = true
flake_path = '/Users/picric_acid/.dotfiles'
flake_config = 'myHomeConfig'
